name: Deploy to remote server

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: sudo apt-get install -y openvpn rsync

      - name: Connect to VPN
        id: vpn_connect
        run: |
          echo "${{ secrets.OPENVPN_CERTIFICATE }}" > ~/redcraft.ovpn
          sudo openvpn --config ~/redcraft.ovpn --daemon

      - name: Check VPN connection
        run: |
          sleep 10 # Wait a few seconds before we check the status
          echo ${{ steps.vpn_connect.outputs.STATUS }}

      - name: Prepare SSH folder
        run: mkdir -p ~/.ssh

      - name: Default testing settings
        run: |
          echo "SSH_HOST=${{ secrets.SSH_HOST_TESTING }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ secrets.SSH_USER_TESTING }}" >> $GITHUB_ENV
          echo "${{ secrets.SSH_PRIVATE_KEY_TESTING }}" > ~/.ssh/id_rsa
          echo "${{ secrets.ENV_FILE_TESTING }}" > .env

      - name: Staging settings
        if: github.ref == 'refs/heads/development'
        run: |
          echo "SSH_HOST=${{ secrets.SSH_HOST_STAGING }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ secrets.SSH_USER_STAGING }}" >> $GITHUB_ENV
          echo "${{ secrets.SSH_PRIVATE_KEY_STAGING }}" > ~/.ssh/id_rsa
          echo "${{ secrets.ENV_FILE_STAGING }}" > .env

      - name: Production settings
        if: github.ref == 'refs/heads/master'
        run: |
          echo "SSH_HOST=${{ secrets.SSH_HOST_PRODUCTION }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ secrets.SSH_USER_PRODUCTION }}" >> $GITHUB_ENV
          echo "${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}" > ~/.ssh/id_rsa
          echo "${{ secrets.ENV_FILE_PRODUCTION }}" > .env

      - name: Copy files to remote
        run: |
          echo "Target server: $SSH_USER@$SSH_HOST"
          sudo route add $SSH_HOST dev tun0
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST service gunicorn stop
          rsync -a --delete . $SSH_USER@$SSH_HOST:/opt/redcraft_website
          ssh $SSH_USER@$SSH_HOST chown -R gunicorn:gunicorn /opt/redcraft_website
          ssh $SSH_USER@$SSH_HOST /opt/redcraft_website/setup.sh
          ssh $SSH_USER@$SSH_HOST service gunicorn start

      - name: Disconnect VPN
        run: sudo killall openvpn
